In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('Duplicate_Barcode_items.csv')

In [5]:
data

,ProductCode,Name,Category,Brand,Type,FixedAssetType,CostingMethod,Length,Width,Height,...,DimensionAttribute1,DimensionAttribute2,DimensionAttribute3,DimensionAttribute4,DimensionAttribute5,DimensionAttribute6,DimensionAttribute7,DimensionAttribute8,DimensionAttribute9,DimensionAttribute10
0,929521009691,(S) Casahana Elegance Mooncake-2H/2PC,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9329521009707-1,(S) CASAHANA Musang King Durian Series Mooncak...,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9329521009707,(S) CASAHANA Musang King Durian Series Mooncak...,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9329521008892-1,(S) CASAHANA Tea House Series Mooncake/1pc,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9329521008892,(S) CASAHANA Tea House Series Mooncake/680g,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2034,HRSHM,東和台灣燒卷Roasted Squid/100g,Canned Food,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2035,NS-39203,茉莉花茶,Snacks,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2036,27305,象麻竹筍片malingbambooshootslices140G,Canned Food,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2037,TWIN108,雙象麻竹筍片 140G Twin Elep Bambo Shoot Slices,Canned Food,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2038,NYG061,韓國17茶..17 Tea/500ml,Drinks,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
sales_history = pd.read_csv('SalesReport.csv')

In [7]:
sales_history

,SKU,Product,Unit,Customer,Sales Representative,Quantity,Invoice,Sale,COGS,Journals,Profit
0,$2 item,$2 item,Each,Default Cash,Tiffany Yuen,1.00,2.00,1.82,0.00,0.0,1.82
1,$5,$5,Each,Default Cash,Davely's Manager,2.00,10.00,9.09,0.00,0.0,9.09
2,(S) Pigeon Jasmine Rice 10kg,Pigeon Jasmine Rice 10kg,Each,(A) Intersection Project,Davely's Manager,1.00,34.00,34.00,12.00,0.0,22.00
3,(S) Pigeon Jasmine Rice 10kg,Pigeon Jasmine Rice 10kg,Each,Default Cash,davelysinternational@gmail.com,1.00,34.00,34.00,12.00,0.0,22.00
4,(S) Pigeon Jasmine Rice 10kg,Pigeon Jasmine Rice 10kg,Each,Default Cash,Tiffany Yuen,1.00,34.00,34.00,12.00,0.0,22.00
...,...,...,...,...,...,...,...,...,...,...,...
24309,YX02,Ye Xing Sliced Dried Noodle/900g,Each,Members Special,Oi,1.00,12.29,12.29,8.75,0.0,3.54
24310,YX02,Ye Xing Sliced Dried Noodle/900g,Each,Members Special,Tiffany Yuen,1.00,12.29,12.29,8.75,0.0,3.54
24311,Zheng Gu Shui,Zheng Gu Shui,Each,Default Cash,Davely's Manager,1.00,17.99,16.35,0.00,0.0,16.35
24312,Zheng Gu Shui,Zheng Gu Shui,Each,Default Cash,Tiffany Yuen,1.00,17.99,16.35,0.00,0.0,16.35
24313,ZQ70467,SUKIYAKI POT,Each,Default Cash,Davely's Manager,1.00,79.99,72.72,52.38,0.0,20.34

## Change the status of the items that are not in the sales history into Deprecate

In [31]:
Deprecation = pd.DataFrame(columns = data.columns)

In [32]:
Deprecation

Empty DataFrame
Columns: [ProductCode, Name, Category, Brand, Type, FixedAssetType, CostingMethod, Length, Width, Height, Weight, CartonLength, CartonWidth, CartonHeight, CartonInnerQuantity, CartonQuantity, CartonVolume, WeightUnits, DimensionUnits, Barcode, MinimumBeforeReorder, ReorderQuantity, DefaultLocation, LastSuppliedBy, SupplierProductCode, SupplierProductName, SupplierFixedPrice, PriceTier1, PriceTier2, PriceTier3, PriceTier4, PriceTier5, PriceTier6, PriceTier7, PriceTier8, PriceTier9, PriceTier10, AssemblyBOM, AutoAssemble, AutoDisassemble, DropShip, DropShipSupplier, AverageCost, DefaultUnitOfMeasure, InventoryAccount, RevenueAccount, ExpenseAccount, COGSAccount, ProductAttributeSet, AdditionalAttribute1, AdditionalAttribute2, AdditionalAttribute3, AdditionalAttribute4, AdditionalAttribute5, AdditionalAttribute6, AdditionalAttribute7, AdditionalAttribute8, AdditionalAttribute9, AdditionalAttribute10, DiscountName, ProductFamilySKU, ProductFamilyName, ProductFamilyOption1Name, ProductFamilyOption1Value, ProductFamilyOption2Name, ProductFamilyOption2Value, ProductFamilyOption3Name, ProductFamilyOption3Value, CommaDelimitedTags, StockLocator, PurchaseTaxRule, SaleTaxRule, Status, Description, ShortDescription, Sellable, PickZones, AlwaysShowQuantity, WarrantySetupName, InternalNote, ProductionBOM, MakeToOrderBom, QuantityToProduce, IsAccountingDimensionEnabled, DimensionAttribute1, DimensionAttribute2, DimensionAttribute3, DimensionAttribute4, DimensionAttribute5, DimensionAttribute6, DimensionAttribute7, DimensionAttribute8, DimensionAttribute9, DimensionAttribute10]
Index: []

[0 rows x 94 columns]

In [33]:
Reserve = pd.DataFrame(columns = data.columns)

In [34]:
Reserve

Empty DataFrame
Columns: [ProductCode, Name, Category, Brand, Type, FixedAssetType, CostingMethod, Length, Width, Height, Weight, CartonLength, CartonWidth, CartonHeight, CartonInnerQuantity, CartonQuantity, CartonVolume, WeightUnits, DimensionUnits, Barcode, MinimumBeforeReorder, ReorderQuantity, DefaultLocation, LastSuppliedBy, SupplierProductCode, SupplierProductName, SupplierFixedPrice, PriceTier1, PriceTier2, PriceTier3, PriceTier4, PriceTier5, PriceTier6, PriceTier7, PriceTier8, PriceTier9, PriceTier10, AssemblyBOM, AutoAssemble, AutoDisassemble, DropShip, DropShipSupplier, AverageCost, DefaultUnitOfMeasure, InventoryAccount, RevenueAccount, ExpenseAccount, COGSAccount, ProductAttributeSet, AdditionalAttribute1, AdditionalAttribute2, AdditionalAttribute3, AdditionalAttribute4, AdditionalAttribute5, AdditionalAttribute6, AdditionalAttribute7, AdditionalAttribute8, AdditionalAttribute9, AdditionalAttribute10, DiscountName, ProductFamilySKU, ProductFamilyName, ProductFamilyOption1Name, ProductFamilyOption1Value, ProductFamilyOption2Name, ProductFamilyOption2Value, ProductFamilyOption3Name, ProductFamilyOption3Value, CommaDelimitedTags, StockLocator, PurchaseTaxRule, SaleTaxRule, Status, Description, ShortDescription, Sellable, PickZones, AlwaysShowQuantity, WarrantySetupName, InternalNote, ProductionBOM, MakeToOrderBom, QuantityToProduce, IsAccountingDimensionEnabled, DimensionAttribute1, DimensionAttribute2, DimensionAttribute3, DimensionAttribute4, DimensionAttribute5, DimensionAttribute6, DimensionAttribute7, DimensionAttribute8, DimensionAttribute9, DimensionAttribute10]
Index: []

[0 rows x 94 columns]

In [35]:
Sales_SKU = list(sales_history['SKU'].unique())
for i in range(len(data)):
    if data['ProductCode'][i] not in Sales_SKU:
        Deprecation.loc[len(Deprecation)] = list(data.loc[i])
    else:
        Reserve.loc[len(Reserve)] = list(data.loc[i])

In [36]:
Deprecation

,ProductCode,Name,Category,Brand,Type,FixedAssetType,CostingMethod,Length,Width,Height,...,DimensionAttribute1,DimensionAttribute2,DimensionAttribute3,DimensionAttribute4,DimensionAttribute5,DimensionAttribute6,DimensionAttribute7,DimensionAttribute8,DimensionAttribute9,DimensionAttribute10
0,4711029,(S) Formosa Selected Walnut Candy/250G,Snacks,Formosa,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NS-42576,(S) Formosa Selected Walnut Candy/250G,Snacks,Formosa,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VIET1001,(S) Fried Pork Cake/500g,Locally Made Delicacies,Local,Non Inventory,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6919839601057,(S) Fu Lin Men Pearl Short Grain Rice/5Kg,Rice,Fulinmen,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,OCT5FruitSingle,(S) OCT5th Fruits & Greentea Mooncake/1pc,Mooncakes,Oct 5th,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1310,RI01K,恆暉泰國黑糯米1KG Heng Fai Black Sticky Rice,Dried Vegetables & Herbs,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1311,HFA1075,日本天花白菇(3.5-4.2cm)..Shiitake Mushroom/400,Dried Vegetables & Herbs,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1312,HRSHM,東和台灣燒卷Roasted Squid/100g,Canned Food,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1313,NS-39203,茉莉花茶,Snacks,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1314,NYG061,韓國17茶..17 Tea/500ml,Drinks,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
len(Deprecation)

1315

In [39]:
len(Reserve)

724

In [38]:
len(data)

2039

In [19]:
Deprecation['Status'] = ['DEPRECATE' for i in range(len(Deprecation))]

In [21]:
Deprecation['Status']

0       DEPRECATE
1       DEPRECATE
2       DEPRECATE
3       DEPRECATE
4       DEPRECATE
          ...
1310    DEPRECATE
1311    DEPRECATE
1312    DEPRECATE
1313    DEPRECATE
1314    DEPRECATE
Name: Status, Length: 1315, dtype: object

In [64]:
Deprecation.to_csv('Deprecation_item.csv', index = False)

In [24]:
Deprecation

,ProductCode,Name,Category,Brand,Type,FixedAssetType,CostingMethod,Length,Width,Height,...,DimensionAttribute1,DimensionAttribute2,DimensionAttribute3,DimensionAttribute4,DimensionAttribute5,DimensionAttribute6,DimensionAttribute7,DimensionAttribute8,DimensionAttribute9,DimensionAttribute10
0,4711029,(S) Formosa Selected Walnut Candy/250G,Snacks,Formosa,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NS-42576,(S) Formosa Selected Walnut Candy/250G,Snacks,Formosa,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,VIET1001,(S) Fried Pork Cake/500g,Locally Made Delicacies,Local,Non Inventory,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6919839601057,(S) Fu Lin Men Pearl Short Grain Rice/5Kg,Rice,Fulinmen,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,OCT5FruitSingle,(S) OCT5th Fruits & Greentea Mooncake/1pc,Mooncakes,Oct 5th,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1310,RI01K,恆暉泰國黑糯米1KG Heng Fai Black Sticky Rice,Dried Vegetables & Herbs,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1311,HFA1075,日本天花白菇(3.5-4.2cm)..Shiitake Mushroom/400,Dried Vegetables & Herbs,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1312,HRSHM,東和台灣燒卷Roasted Squid/100g,Canned Food,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1313,NS-39203,茉莉花茶,Snacks,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1314,NYG061,韓國17茶..17 Tea/500ml,Drinks,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
Reserve

,ProductCode,Name,Category,Brand,Type,FixedAssetType,CostingMethod,Length,Width,Height,...,DimensionAttribute1,DimensionAttribute2,DimensionAttribute3,DimensionAttribute4,DimensionAttribute5,DimensionAttribute6,DimensionAttribute7,DimensionAttribute8,DimensionAttribute9,DimensionAttribute10
0,929521009691,(S) Casahana Elegance Mooncake-2H/2PC,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9329521009707-1,(S) CASAHANA Musang King Durian Series Mooncak...,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9329521009707,(S) CASAHANA Musang King Durian Series Mooncak...,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9329521008892-1,(S) CASAHANA Tea House Series Mooncake/1pc,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9329521008892,(S) CASAHANA Tea House Series Mooncake/680g,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,4901111844872Zeitaku,Zeitaku Luxury Drip Pack Special Blend/8pcs,Tea & Coffee,Zeitaku,Stock,NaN,FIFO,10,10,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,JACK1001,ZhenZhen Potato Chip Octopus/50g,Snacks,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
721,SDI001,ZHJ Seasoned Coating Mix For Frying/120G,1029,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,27305,象麻竹筍片malingbambooshootslices140G,Canned Food,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
723,TWIN108,雙象麻竹筍片 140G Twin Elep Bambo Shoot Slices,Canned Food,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
Reserve['Barcode'].value_counts()

929521009691     3
9555118601836    3
4710874020139    3
4902750362543    3
4892030045191    3
                ..
4901085599891    1
4901085184714    1
835143011749     1
835143001832     1
48930079         1
Name: Barcode, Length: 615, dtype: int64

## Create a file with active item duplicate barcode

In [56]:
Active = pd.DataFrame(columns = data.columns)
duplicate_barcode = list(Reserve['Barcode'].unique())
for i in duplicate_barcode:
    if len(Reserve[Reserve['Barcode'] == i]) > 1:
        Active = Active.append(Reserve[Reserve['Barcode'] == i])

C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])

C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])
C:\Users\n10941576\AppData\Local\Temp\ipykernel_11712\1402784377.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Active = Active.append(Reserve[Reserve['Barcode'] == i])

In [57]:
Active = Active.reset_index()

In [58]:
Active.pop('index')

0        0
1       40
2       41
3        1
4        2
      ...
208    697
209    708
210    709
211    722
212    723
Name: index, Length: 213, dtype: int64

In [59]:
Active

,ProductCode,Name,Category,Brand,Type,FixedAssetType,CostingMethod,Length,Width,Height,...,DimensionAttribute1,DimensionAttribute2,DimensionAttribute3,DimensionAttribute4,DimensionAttribute5,DimensionAttribute6,DimensionAttribute7,DimensionAttribute8,DimensionAttribute9,DimensionAttribute10
0,929521009691,(S) Casahana Elegance Mooncake-2H/2PC,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CH2B,(S)Casahana Elegance Mooncake-2B/2PC,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CH2E,(S)Casahana Elegance Mooncake-2E/2PC,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9329521009707-1,(S) CASAHANA Musang King Durian Series Mooncak...,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9329521009707,(S) CASAHANA Musang King Durian Series Mooncak...,Mooncakes,Casahana,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,CBWWMWL2Y,WINGWAH M/CAKE-WHITE LOTUS 2Y/740G,Other,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,4712586000447,Yi Feng Crystal Sugar/360g,Spices & Condiments,Yi Feng,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,GYF013,Yi Feng Crystal Sugar/360g,1023,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,27305,象麻竹筍片malingbambooshootslices140G,Canned Food,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,TWIN108,雙象麻竹筍片 140G Twin Elep Bambo Shoot Slices,Canned Food,NaN,Stock,NaN,FIFO,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
Active.to_csv('Active.csv', index = False)

In [63]:
Active['Barcode'].unique()

array(['929521009691', '9329521009707', '9329521008892', '1993', '103',
       '4710685443837', '9328297000048', '6935133801375', '6944352800465',
       '8016', '9317906001514', '9315697897866', '4264872950634',
       '0793618315795', '6973076671457', '635133800668', '4891267000508',
       '2950601010008', '4710174006352', '8850153333003', '8850035001020',
       '6958770001403', '4905671220251', '4908209119034', '4710128023022',
       '8935034312114', '9313551550506', '4970030918643', '6927777513097',
       '4714221130786', '8996001410691', '8003', 'X0010W4FZ3',
       '084909004383', '4521184111284', '6927119000216', '4902750362543',
       '8809122934222', '8886001200197', '4901326040359', '4901410065343',
       '087703324114', '8854241009412', '4901005511163', '9555118601836',
       '9329937005416', '4710176011194', '9329998002461', '4902888973659',
       '9588552319937', '4711202220733', '4711202220061', '6906839701016',
       '793618170103', '4710057204783', '2012001000000', '4710126184299',
       '089686440089', '835143012326', '8850643028129', '4710515531291',
       '9319224804051', '4971922352798', '31977519615', '025407803917',
       '4710254508592', '4514410604551', '8996001340325', '6900873039203',
       '4710421072420', '8850718817351', '8852008511239', '9310432003649',
       '4710678230314', '4710678230321', '8888077101101', '4892030071626',
       '4892030045191', '9347434000147', '6900873255443', '4711202220108',
       '4710515535435', '8850370721119', '4088700060216', '9335388000054',
       '4714379990263', '4714379990089', '4714379990096', '4987035338710',
       '4710874020139', '8801073141780', '4710515530638', '4710095958006',
       '9333406000277', '9310432000631', '4710105330372', '8859532700078',
       '4904710418246', '6902083881085', '6956367338680', '021348321022',
       '021348321015', '4712586000447', '8851011216339'], dtype=object)